name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Prettier check
      id: prettier-check
      run: npm run format:check
      continue-on-error: true

    - name: Auto-fix formatting if needed
      if: steps.prettier-check.outcome == 'failure'
      run: |
        echo "Formatting issues found. Auto-fixing..."
        npm run format
        echo "Code has been auto-formatted"

    - name: Verify formatting after fix
      if: steps.prettier-check.outcome == 'failure'
      run: npm run format:check

    - name: Commit formatted code
      if: steps.prettier-check.outcome == 'failure' && github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-format code with Prettier [skip ci]"
          git push
        fi

    - name: Run ESLint
      run: npm run lint

    - name: Auto-fix ESLint issues
      if: failure()
      run: |
        echo "ESLint issues found. Attempting auto-fix..."
        npm run lint:fix
        echo "ESLint auto-fix completed"

    - name: Run TypeScript check
      run: npm run type-check

    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_CONVEX_URL: ${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
        CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
        LIVEBLOCKS_SECRET_KEY: ${{ secrets.LIVEBLOCKS_SECRET_KEY }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-files-${{ matrix.node-version }}
        path: .next/
        retention-days: 1

  format-and-lint-fix:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Prettier format
      run: npm run format

    - name: Run ESLint fix
      run: npm run lint:fix

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No formatting changes needed"
        else
          git commit -m "Auto-format and lint-fix code [skip ci]"
          git push
        fi